name: CI

on:
    push:
        branches: [master]
    pull_request:

jobs:
    test:
        name: Commit Validation
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install packages
              run: yarn

            - name: Check lint
              run: yarn lint

            - name: Run tests
              run: yarn test --watchAll=false --coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
